
version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - ./data:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=HhsafCedAhtm
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
